# Site
name: '东风面软件站'
description: >- # this means to ignore newlines until "baseurl:"
  东风面软件站是应用程序分享站，包含大量macOS、Windows、Linux等平台的各种破解软件资源。
  还包含一些互联网资源搜索等原创教程。
  更多好玩，等你发现！
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dfface.com" # the base hostname & protocol for your site, e.g. http://example.com
disqus: 'dfface'
email: 'admin@dfface.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
 
# Authors
authors:
    dfface:
      name:           dfface
      site:           https://dfface.com
      avatar:         assets/images/avatar1.jpg
      bio:            "Hi, I am Sal, the author of Mundana, the theme you're currently previewing. I hope you like it!"
      email:          admin@dfface.com
      twitter:        https://twitter.com/dfface_official

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: dfface
      avatar: assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# sass
sass:
  sass_dir: assets/css # Override jekyll default path '/_sass'
  style:  compressed

# Jekyll-HTML-Compressor
compress_html:
  clippings: []
  comments: []
  endings: []
  profile: false
  blanklines: true
  ignore:
    envs: []


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]