# Site
name: '东风面资源站'
description: >- # this means to ignore newlines until "baseurl:"
  东风面资源站是应用程序分享站，包含大量macOS、Windows、Linux等平台的各种破解资源资源。
  还包含一些互联网资源搜索等原创教程。
  更多好玩，等你发现！
logo: '/i.loli.net/2019/11/25/OKMVDuRHgSXtGPo.png'
favicon: 'https://res.cloudinary.com/dfface/image/upload/v1574931690/dfface.com/favicon_ftcsug.ico'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dfface.com" # the base hostname & protocol for your site, e.g. http://example.com
disqus: 'dfface'
valine_appID: yIIXAp48OTFNRpKE3Yz1uw82-MdYXbMMI
valine_appKey: KVQycwd5Wici3VNz0lOHP64I
email: 'admin@dfface.com'
mailchimp-list: https://dfface.mailchimpsites.com/

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
 
# Authors
authors:
    dfface:
      name:           dfface
      site:           https://dfface.com
      avatar:         /i.loli.net/2019/11/25/cGinHEsvpqhBaUP.png
      bio:            "Hi，我是东风面(dfface)，是你正在浏览的东风面资源站的站长。我希望你喜欢它，如有任何建议，请给我留言或发送邮件等。"
      email:          admin@dfface.com
      twitter:        https://www.jianshu.com/u/3c54a64f5b13

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: dfface
      avatar: /i.loli.net/2019/11/25/cGinHEsvpqhBaUP.png
      image: /i.loli.net/2019/11/25/mep8TflXZUd9Yb5.png
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# sass
sass:
  sass_dir: assets/css # Override jekyll default path '/_sass'
  style:  compressed

# Jekyll-HTML-Compressor
compress_html:
  clippings: []
  comments: []
  endings: []
  profile: false
  blanklines: true
  ignore:
    envs: []


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]